### ISSUE TITLE
'SchemaOC4IDS' object has no attribute 'release_pkg_schema_url'

### ISSUE THREAD

**Issue by michaelwood** [open-contracting/cove-oc4ids#66]
Think this is because the variable has been renamed in schema.py on libcoveoc4ids.

```
ERROR 2020-09-30 16:40:40,061 log 39501 139934219638528 Internal Server Error: /infrastructure/review/data/6c45c26d-b6e8-427f-b136-a06dba00c849
Traceback (most recent call last):
  File "/home/michael/dev/ods/cove-oc4ids/.ve/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/michael/dev/ods/cove-oc4ids/.ve/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/michael/dev/ods/cove-oc4ids/.ve/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/michael/dev/ods/cove-oc4ids/cove_oc4ids/views.py", line 25, in wrapper
    return func(request, *args, **kwargs)
  File "/home/michael/dev/ods/cove-oc4ids/cove_oc4ids/views.py", line 82, in explore_oc4ids
    pkg_schema_url=schema_oc4ids.release_pkg_schema_url))
AttributeError: 'SchemaOC4IDS' object has no attribute 'release_pkg_schema_url'
```

Steps to reproduce:
1. Upload a .xlsx to cove

**Comment by Bjwebb** [comment]
Yes, this is renamed to `pkg_schema_url`.

I think I missed this because the tests don't cover spreadsheet upload.
